### ISSUE TITLE
libImaging as C functions ?

### ISSUE THREAD

**Issue by CodeByMaxx** [uploadcare/pillow-simd#46] opened 2018-12-31 16:16 UTC
Is there a simple way to use libImaging as C  functions in a c program. I mainly interested in those 
functions. 
I mainly interested in the ImageStretch Function like here 

https://github.com/python-pillow/Pillow/blob/2.6.2/_imaging.c#L1635

static PyObject*
_stretch(ImagingObject* self, PyObject* args)
{
    Imaging imIn;
    Imaging imTemp;
    Imaging imOut;

    int xsize, ysize;
    int filter = IMAGING_TRANSFORM_NEAREST;
    if (!PyArg_ParseTuple(args, "(ii)|i", &xsize, &ysize, &filter))
    return NULL;

    imIn = self->image;

    /* two-pass resize: minimize size of intermediate image */
    if ((Py_ssize_t) imIn->xsize * ysize < (Py_ssize_t) xsize * imIn->ysize)
        imTemp = ImagingNew(imIn->mode, imIn->xsize, ysize);
    else
        imTemp = ImagingNew(imIn->mode, xsize, imIn->ysize);
    if (!imTemp)
        return NULL;

    /* first pass */
    if (!ImagingStretch(imTemp, imIn, filter)) {
        ImagingDelete(imTemp);
        return NULL;
    }

    imOut = ImagingNew(imIn->mode, xsize, ysize);
    if (!imOut) {
        ImagingDelete(imTemp);
        return NULL;
    }

    /* second pass */
    if (!ImagingStretch(imOut, imTemp, filter)) {
        ImagingDelete(imOut);
        ImagingDelete(imTemp);
        return NULL;
}

because in https://github.com/python-pillow/Pillow/blob/master/src/libImaging/Imaging.h is defined and i want to know how to fill right the instance of  imIn. Are there any load functions which i can use in a c/c++ programm or something like that. A simple C/C++ Interface  would be nice.

**Comment by homm** [comment] 2020-01-26 15:20
Duplicate of #32

**Closed as completed by homm** 2020-01-26 15:20 UTC
